/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testIsPalindrome() {
        assertTrue(App.isPalindrome("abc cba"));
        assertTrue(App.isPalindrome("よく利くよ"));
        assertFalse(App.isPalindrome("Was it a rat I saw"));
        assertTrue(App.isPermutationOfPalindrome("Rats live on no evil star"));
        assertTrue(App.isPermutationOfPalindromeBetter("Zeus was deified, saw Suez"));
        assertTrue(App.isPermutationOfPalindromeBit("Nurses run"));
    }
}
