/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testIsCharDuplicated() {
        assertTrue(App.isCharDuplicated("aaa"));
        assertFalse(App.isCharDuplicated("aABbCc"));
        assertFalse(App.isCharDuplicated("abcdefghijklmnopqrstuvwxyz1234567890!\"#$%&'()~=|-^[@`{]:;+*}/.,<>\\?_ABCDEFGHIJKLMNOPQRSTUVWXYZ"));
        assertTrue(App.isCharDuplicated("あいうえおあ"));
        assertFalse(App.isCharDuplicated("あiうeおa"));
        assertTrue(App.isCharDuplicated(":a:"));
    }

    @Test public void testIsUniqueChars() {
        assertFalse(App.isUniqueChars("aaa"));
        assertTrue(App.isUniqueChars("aABbCc"));
        assertTrue(App.isUniqueChars("abcdefghijklmnopqrstuvwxyz1234567890!\"#$%&'()~=|-^[@`{]:;+*}/.,<>\\?_ABCDEFGHIJKLMNOPQRSTUVWXYZ"));
        assertFalse(App.isUniqueChars("あいうえおあ"));
        assertFalse(App.isUniqueChars("あiうeおa"));
        assertFalse(App.isUniqueChars(":a:"));
    }
}
